### ISSUE TITLE
Please provide info on smiling2.jar

### ISSUE THREAD

**Issue by rkrysinski** [Asiorek/DriftDetector#1]
Could you lease provide some background on the smiling2.jar file. In particular from where it was taken, perhaps a website for start would be enough.

**Comment by j-partyka** [comment]
smiling2.jar is irrelevant for now, I've just delete it from the do_not_use branch. 
Eventually, I would like to put modules: math, core and data from this library: https://github.com/haifengl/smile into this Android project.

**Comment by rkrysinski** [comment]
ok, normally jars should not be placed into repository unless there is a very good reason for that. I was going to investigate whether or not there is possibility to get rid of the jar from repo and put it into gradle dependency section. 

But if this is irrelevant then let's move forward. The problem that Lukasz highlighted is connected with compilation:

```
Lambda coming from jar file need their interfaces on the classpath to
be compiled, unknown interfaces are java.util.function.Function
```

Function is something introduced in core java8, which suggests that you might have java version less than 8 configured on your platform.  To ensure that gradle should use java8 for compilation you should probably set compile options like:

```
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```

But one way or the other java8 sdk must be available on your platform and configured either via environmental variables or gradle.properties file.

Should you have any questions do not hesitate to write.

**Comment by j-partyka** [comment]
I have installed java-8-oracle in my system and set in Project Structure of Android project the path to it. In build.gradle I have also set these compileOptions for java8. 
However maybe I should also change sth in gradle.properties file. What should be put there?

**Comment by rkrysinski** [comment]
It looks that java8 needs to be explicitly enabled for android apps, I've made the following change to build.gradle file:

```
diff --git a/app/build.gradle b/app/build.gradle
index 9f57f21..b6976b6 100644
--- a/app/build.gradle
+++ b/app/build.gradle
@@ -10,7 +10,15 @@ android {
         versionCode 1
         versionName "1.0"
         testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
+        jackOptions {
+            enabled true
+        }
+    }
+    compileOptions {
+        sourceCompatibility JavaVersion.VERSION_1_8
+        targetCompatibility JavaVersion.VERSION_1_8
     }
+
     buildTypes {
         release {
             minifyEnabled false

```

Try with this configuration and let me know if this helps.

**Comment by j-partyka** [comment]
I've already tried with these changes, but it's still not working.
They are implemented in "do_not_use" branch.
It's set as "do_not_use" only to keep in mind that it is not working yet branch.

**Comment by rkrysinski** [comment]
OK, problem reproduced, will look into it later on.

**Comment by j-partyka** [comment]
Thank you!

**Comment by rkrysinski** [comment]
Well, according to this issue against Android Open Source https://code.google.com/p/android/issues/detail?id=211386

```
Jack supports Java 8 in library modules, but only lambdas can be used if minSdk < 24. Gradle still has some work to support this.

java.util.function is only available on N and above, since the runtime doesn't include it on earlier platforms.
```

I've tried the hacks described in the issue but without success.

Couple of options:

1. Wait until Google fix this issue
2. Use maven instead of gradle
3. Refactor smile-math to not use java.util.function.Function
4. Find different library compatible with java7

The item #3 is actually not as hard as it sounds, attached is a diff
[patch.diff.zip](https://github.com/Asiorek/DriftDetector/files/671388/patch.diff.zip) with my changes.
Of course its hard to name it refactoring since I commented out code that has reference to Function, but after compilation putting it into android studio libs, the gradle compilation worked. From the other hand I don't know smile-maths thus not sure if commented out methods are crucial for you or not. This may buy you some time and move forward with your work, and when google fixes the issue you can use official version of smile-math after all. 

Hope that helps.

**Comment by j-partyka** [comment]
I followed your 3rd advice, refactored smile-math and set this and my stream module as the external modules in my android application. This application is for testing purposes for my engineering thesis. Now it works! Thank your for your time and effort.
Merry Christmas! :D

**Comment by rkrysinski** [comment]
OK thanks, I'm glad that I could help.
